name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Use cached dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy

      - name: Run flake8 (Linting)
        run: |
          pipenv run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Use cached dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy

      - name: Run tests with pytest
        run: |
          pipenv run pytest --maxfail=1 --disable-warnings -q
